// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaCaminhao.Data;

namespace ProvaCaminhao.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20220314193927_caminhaoModelo")]
    partial class caminhaoModelo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProvaCaminhao.Models.Caminhao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("modeloID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("modeloID");

                    b.ToTable("caminhao");
                });

            modelBuilder.Entity("ProvaCaminhao.Models.Modelo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("modelo");
                });

            modelBuilder.Entity("ProvaCaminhao.Models.Caminhao", b =>
                {
                    b.HasOne("ProvaCaminhao.Models.Modelo", "modelo")
                        .WithMany()
                        .HasForeignKey("modeloID");
                });
#pragma warning restore 612, 618
        }
    }
}
